"""Company names for well-known NSE symbols.

021's instrument file has no company names, only trading symbols, so "Infosys" would never find INFY.
This small table lets the trader say the name. It only helps people find a stock: the symbol in the
instrument file is the authority for everything that matters (token, tick size, price band)."""

NAMES: dict[str, str] = {
    "RELIANCE": "Reliance Industries Ltd",
    "TCS": "Tata Consultancy Services Ltd",
    "INFY": "Infosys Ltd",
    "HDFCBANK": "HDFC Bank Ltd",
    "ICICIBANK": "ICICI Bank Ltd",
    "SBIN": "State Bank of India",
    "BHARTIARTL": "Bharti Airtel Ltd",
    "ITC": "ITC Ltd",
    "KOTAKBANK": "Kotak Mahindra Bank Ltd",
    "LT": "Larsen & Toubro Ltd",
    "HINDUNILVR": "Hindustan Unilever Ltd",
    "AXISBANK": "Axis Bank Ltd",
    "BAJFINANCE": "Bajaj Finance Ltd",
    "BAJAJFINSV": "Bajaj Finserv Ltd",
    "BAJAJ-AUTO": "Bajaj Auto Ltd",
    "MARUTI": "Maruti Suzuki India Ltd",
    "ASIANPAINT": "Asian Paints Ltd",
    "SUNPHARMA": "Sun Pharmaceutical Industries Ltd",
    "TITAN": "Titan Company Ltd",
    "ULTRACEMCO": "UltraTech Cement Ltd",
    "WIPRO": "Wipro Ltd",
    "NESTLEIND": "Nestle India Ltd",
    "ONGC": "Oil and Natural Gas Corporation Ltd",
    "NTPC": "NTPC Ltd",
    "POWERGRID": "Power Grid Corporation of India Ltd",
    "TATAMOTORS": "Tata Motors Ltd",
    "TATASTEEL": "Tata Steel Ltd",
    "TATACONSUM": "Tata Consumer Products Ltd",
    "TATAPOWER": "Tata Power Company Ltd",
    "TATAELXSI": "Tata Elxsi Ltd",
    "TATACOMM": "Tata Communications Ltd",
    "TECHM": "Tech Mahindra Ltd",
    "HCLTECH": "HCL Technologies Ltd",
    "M&M": "Mahindra & Mahindra Ltd",
    "ADANIENT": "Adani Enterprises Ltd",
    "ADANIPORTS": "Adani Ports and Special Economic Zone Ltd",
    "COALINDIA": "Coal India Ltd",
    "JSWSTEEL": "JSW Steel Ltd",
    "HINDALCO": "Hindalco Industries Ltd",
    "GRASIM": "Grasim Industries Ltd",
    "DRREDDY": "Dr. Reddy's Laboratories Ltd",
    "CIPLA": "Cipla Ltd",
    "EICHERMOT": "Eicher Motors Ltd",
    "HEROMOTOCO": "Hero MotoCorp Ltd",
    "BPCL": "Bharat Petroleum Corporation Ltd",
    "BRITANNIA": "Britannia Industries Ltd",
    "DIVISLAB": "Divi's Laboratories Ltd",
    "APOLLOHOSP": "Apollo Hospitals Enterprise Ltd",
    "INDUSINDBK": "IndusInd Bank Ltd",
    "SBILIFE": "SBI Life Insurance Company Ltd",
    "HDFCLIFE": "HDFC Life Insurance Company Ltd",
    "ZOMATO": "Zomato Ltd",
    "ETERNAL": "Eternal Ltd (formerly Zomato)",
    "PAYTM": "One 97 Communications Ltd (Paytm)",
    "IRCTC": "Indian Railway Catering and Tourism Corporation Ltd",
    "VEDL": "Vedanta Ltd",
    "YESBANK": "Yes Bank Ltd",
    "IDEA": "Vodafone Idea Ltd",
    "DMART": "Avenue Supermarts Ltd (DMart)",
    "PIDILITIND": "Pidilite Industries Ltd",
    "HAVELLS": "Havells India Ltd",
    "LTIM": "LTIMindtree Ltd",
    "PNB": "Punjab National Bank",
    "BANKBARODA": "Bank of Baroda",
    "IOC": "Indian Oil Corporation Ltd",
    "GAIL": "GAIL (India) Ltd",
    "SAIL": "Steel Authority of India Ltd",
    "HAL": "Hindustan Aeronautics Ltd",
    "BEL": "Bharat Electronics Ltd",
    "LICI": "Life Insurance Corporation of India",
}
